### ISSUE TITLE
Update - 선수 데이터베이스 삽입 기능 구현

### ISSUE THREAD

**Issue by eliotjang** [eliotjang/futsal-online-project#5]
- MySQL에 DB 직접 삽입
- 선수 테이블
  - 선수 아이디 (복합 키)
  - 강화 레벨 (복합 키)
  - 선수 이름
  - 속력
  - 골 결정력
  - 슛 파워
  - 수비
  - 스태미너
  - 희귀도 : 0 ~ 5
    - 0티어부터 5티어까지 존재
  - 가치
    - 캐시
- 한 번에 준비해서 엑셀로 DB에 추가
    - 0강 ~ 5강까지의 모든 강화 선수
- 선수 아이디, 강화 레벨 복합 키 사용

**Comment by ydh1503** [comment]
데이터 베이스 player 테이블에 데이터 추가
-  선수 아이디 1 ~ 180
- 강화 레벨 0 ~ 5
- 각 스탯 피파4 데이터 참고
- 희귀도 0 ~ 5
- 가치 1000 * (희귀도+1)

~~확인 후 이슈 닫아주시면 될 것 같습니다.~~

**Comment by ydh1503** [comment]
이슈 발생 - 복합키(PK: (player_id, upgrade_level)) 구현에 따른 player_id 컬럼 변경 필요
- 현재 총 데이터 개수 : 180 ( 선수 30 * 강화 0~5 )
- 현재 player_id : 1~180
- 복합키 구현 시 같은 선수끼리 같은 player_id 사용 필요
- 수정 후 예상 기대 값 player_id : 1~30

**Comment by eliotjang** [comment]
### dev 브랜치 즉시 반영 사항

- 선수 데이터베이스 복합키 적용

### 변경 전

![화면 캡처 2024-06-01 121350](https://github.com/eliotjang/futsal-online-project/assets/37320831/fc2603ec-d06e-4172-b557-ba85bc7a92bb)


### 변경 후

![변경후](https://github.com/eliotjang/futsal-online-project/assets/37320831/77624b3d-d6ce-4f51-8256-7d1c500a54fb)

**Comment by ydh1503** [comment]
선수 목록(player 테이블) 수정 완료
### 변경 전
![image](https://github.com/eliotjang/futsal-online-project/assets/84895591/0b2b216b-c014-4cdd-acd4-c21d3cefb280)

### 변경 후
![image](https://github.com/eliotjang/futsal-online-project/assets/84895591/f2c59109-929a-45da-ab03-e7fab04989e5)
