### ISSUE TITLE
Update - 출전 선수 명단 구성 / 조회 API 기능 구현

### ISSUE THREAD

**Issue by eliotjang** [eliotjang/futsal-online-project#8]
### Update - 출전 선수 명단 구성 / 조회 API 기능 구현

- 캐릭터와 팀은 1 대 1 관계
    - 출전 선수 명단 테이블
        - 캐릭터 아이디(외래키)
        - 선수 아이디 1
        - 선수 아이디 2
        - 선수 아이디 3
- 팀 구성 시 캐릭터의 해당 선수 보유 여부 확인
- 팀 내 동일 선수 불가
- API URL : `POST /api/roster` (팀 등록), `GET /api/roster` (팀 조회)
    - 팀 조회는 인증 미들웨어 X

### 와이어프레임

![image](https://github.com/eliotjang/futsal-online-project/assets/37320831/7a676f15-9e08-44bf-912a-aa7eff8035bb)

**Comment by ydh1503** [comment]
> 이슈 발생 - 출전 선수 명단 테이블과 보유 선수 목록 테이블 간의 연관 관계 재정립 필요

  - 출전 선수 명단 테이블이 선수 테이블과 관련된 외래키(`player_id, upgrade_level`)와 접점이 없기 때문에 데이터를 불러오기 위해선 순수하게 보유 선수 목록 테이블에 의존하게 됨

  - 만약 출전 선수에 포함된 `character_player_id`가 포함된 row가 보유 선수 목록 테이블에서 제거됐을 경우, 두 테이블 간엔 연관 관계가 없기 때문에 출전 선수 테이블의  `character_player_id`는 유지되나 참조할 테이블의 row가 없어졌기 때문에 오류 발생 ( 데이터베이스 내부 데이터에 대한 신뢰성 감소)
  
> 해결 방법

1.   출전 선수 명단 테이블을 보유 선수 목록 테이블을 부모로 하는 1 : N 관계 테이블로 재정의
    1-1. 현재 테이블을 유지하고 `character_player_id1~3`을 전부 외래키로 설정하는 방법
                   => 보유 선수 목록 테이블에 `onDelete:RESTRICT` 옵션 추가 필요(참조 중인 테이블있을 시 삭제 제한 옵션)
    1-2. 현재 테이블을 파기하고 테이블에 `character_player_id`과 `character_id`를 가진 row를 한 팀 당 출전 선수 인원 수(3)만큼 추가하는 방법
                   => 한 캐릭터 당 한 팀 당 출전 선수 인원 수(3)만큼의 row 수를 유지할 필요가 있음 or 인원 수 검증 로직 추가 필요
2.   출전 선수 명단 테이블에 보유 선수 목록과 관련된 character_player_id를 제거하고 전체 선수 테이블에서 외래키(`player_id, upgrade_level`) 쌍을 추가
