### ISSUE TITLE
피드백

### ISSUE THREAD

**Issue by Ho-yeong** [eliotjang/futsal-online-project#91]
# 총평
- 버튼으로 프론트엔드까지 만든것 너무 재밌어보이네요. 사실 현업에서도 그런식으로 버튼으로 구성된 테스트화면을 만들고는 합니다. (가끔)
- 상당히 고민많이 하셨고 상당히 머리 쓴게 보이는 아주 재밌는 프로젝트였습니다.

---
1. 라우터가 너무 많아요.
https://github.com/eliotjang/futsal-online-project/blob/af5765233bcad4b9b6425ff35f1a6405f358862b/src/app.js#L33-L55
- 물론 이렇게 쓰면 안되는건 아닙니다. 현재 잘 작동하고 있으니 상관은 없습니다만 유지보수를 위해서 조금 더 효율적으로 작성할 필요가 있습니다.
```
const characterRouters = [
  DataCharacterRosterRouter,
  DataCharacterPlayerRouter,
  RosterRouter,
  DrawRouter,
  UpgradeRouter,
];

const accountRouters = [
  AccountRouter,
  InfoRouter,
  CashRouter,
  PlayerRouter,
  ReleaseRouter,
];

const dataRouters = [
  DataPlayerRouter,
  RankingSystemRouter,
  RankGameRouter,
  GameRouter,
  TransferRouter,
  TradingRouter,
];

// 최상위 app.use에 라우터 그룹을 인자로 넣기
app.use('/api/character', characterRouters);
app.use('/api/account', accountRouters);
app.use('/api/data', dataRouters);
```
2. 변하지 않는 값들은 상수로 저장해서 관리하는 것이 좋습니다. 
https://github.com/eliotjang/futsal-online-project/blob/af5765233bcad4b9b6425ff35f1a6405f358862b/src/routes/character/content/futsal/game.router.js#L94-L98
- 이 후 해당 값을 변경해야하는 일이 발생할 경우 상당히 귀찮아질 가능성이 있습니다. 
- 프로젝트가 커져감에 따라서 유지보수 측면을 더욱 고려할 필요가 있습니다.

3. 모의로 경기 하는 건데 랜덤값으로 숫자 '90' 채우는 것을 1경기라고 하는게 재밌네요

**Comment by eliotjang** [comment]
넵, 피드백 감사합니다!
